-- Up migration
ALTER TABLE cars ADD COLUMN IF NOT EXISTS photos JSONB NOT NULL DEFAULT '[]';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS body_type TEXT NOT NULL DEFAULT 'sedan';

-- Down migration
ALTER TABLE cars DROP COLUMN IF EXISTS photos;
ALTER TABLE cars DROP COLUMN IF EXISTS body_type;